#!/usr/bin/env python3
"""
Write a script that lists all databases in MongoDB.
"""
from pymongo import MongoClient

# Connect to the local MongoDB server
client = MongoClient()

# Get a list of all databases on the server
db_list = client.list_database_names()

# Print the list of databases
print("Databases:")
for db_name in db_list:
    print("- {}".format(db_name))

